spring:
  application:
    name: blog
  datasource:
    url: jdbc:mysql://106.14.156.120:3306/blog?characterEncoding=utf8
    username: blog
    password: blog
  jpa:
    show-sql: true
logging:
  file: ./logs/${spring.application.name}.log

sftp:
  ip: 106.14.156.120
  password: Blog_sftp123
  user-name: sftp4Blog
  port: 22